const form=document.querySelector('#chatForm');const input=document.querySelector('#messageInput');const messages=document.querySelector('#messages');const quickQuestions=document.querySelector('#quickQuestions');
const answers=[
 {test:/what is nexa|what do you do|product/i,answer:'Nexa is a calm, connected workspace for ambitious teams. It brings priorities, project context, and helpful AI into one place so your team can move from idea to impact with less friction.'},
 {test:/help teams|team|collaborat|align|workflow/i,answer:'Nexa gives everyone a shared view of the work: clear priorities, lightweight workflows, and the context behind every decision. That means fewer status meetings and more meaningful progress.'},
 {test:/price|cost|plan|free/i,answer:'Nexa offers flexible plans for growing teams. The best place to start is a quick conversation with our team — they can recommend the right setup for your goals.'},
 {test:/random|something fun|interesting|fact/i,answer:'Random fact: honey never really spoils. Archaeologists have found edible honey in ancient Egyptian tombs — it can last for thousands of years when sealed properly.'},
 {test:/hello|hi|hey/i,answer:'Hey! Welcome to Nexa. I can tell you about the product, teamwork, productivity, or answer a completely random question.'},
 {test:/thank/i,answer:'You’re welcome! Keep the good questions coming.'}
];
function answerFor(text){const found=answers.find(item=>item.test.test(text));return found?found.answer:`That’s a thoughtful question. I’m the Nexa product guide, so I can help with our workspace, team productivity, or a random question. Try asking “How does Nexa help teams?”`}
function addMessage(text,type){const row=document.createElement('div');row.className=`chat-message ${type}`;if(type==='bot')row.innerHTML='<span class="bot-avatar">✦</span><p></p>';else row.innerHTML='<p></p>';row.querySelector('p').textContent=text;messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
function send(text){const value=text.trim();if(!value)return;addMessage(value,'user');input.value='';input.focus();const typing=document.createElement('div');typing.className='chat-message bot';typing.id='typing';typing.innerHTML='<span class="bot-avatar">✦</span><p>Thinking…</p>';messages.appendChild(typing);messages.scrollTop=messages.scrollHeight;setTimeout(()=>{typing.remove();addMessage(answerFor(value),'bot')},550)}
form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});quickQuestions.addEventListener('click',e=>{const button=e.target.closest('button');if(button)send(button.dataset.prompt)});document.querySelector('.menu-button').addEventListener('click',()=>document.querySelector('.main-nav').classList.toggle('open'));
